services:
  chatbot:
    build: .
    container_name: rag_chatbot
    ports:
      - "8003:8000"
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db  # Thay đổi từ faiss_index sang chroma_db
    tty: true 
    stdin_open: true
    restart: always
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY} # Thêm biến này để CI/CD truyền key vào