services:
  chatbot:
    build: .
    container_name: rag_chatbot
    ports:
      - "8003:8000"
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
    # Dùng lệnh này để giữ container luôn chạy ngay cả khi server lỗi, giúp bạn vào bash
    tty: true 
    stdin_open: true
    restart: always
    environment:
      - MKL_SERVICE_FORCE_INTEL=1