version: "3.8"

services:
  rag_chatbot:
    build: .
    image: rag_img
    container_name: rag_chatbot
    ports:
      - "8003:8000"
    restart: always
    volumes:
      - shared_data_fastapi_node:/app/data
    env_file:
      - .env
    networks:
      - crm_network

# Kết nối vào Docker Network dùng chung của hệ thống
networks:
  crm_network:
    external: true
volumes:
  shared_data_fastapi_node: # Docker Compose sẽ tự động tạo volume này nếu chưa tồn tại