name: Deploy Chatbot Microservice

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        env:
            DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
            NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          DEPLOY_DIR="/root/chatbot_root/chatbot"
          rm -rf $DEPLOY_DIR
          cp -r . $DEPLOY_DIR
          cd $DEPLOY_DIR
          
          # Ghi file .env tạm thời cho Container đọc
          echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" > .env
          echo "NVIDIA_API_KEY=$NVIDIA_API_KEY" >> .env
          echo "POSTGRES_DB=$POSTGRES_DB" >> .env
          echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
          echo "REDIS_URL=$REDIS_URL" >> .env

          docker compose down
          docker compose up -d --build
