name: Deploy Chatbot
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # 1. Chuyển sang self-hosted để dùng runner trên server của bạn
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        run: |
          cd /root/chatbot_root/chatbot
          # Dùng git pull để nhận code mới nhất thay vì xóa và copy lại
          git pull origin main
          # Dừng và khởi động lại
          docker compose down
          docker compose up -d --build